

name: Deploy Development

on:
  push:
    branches: [development]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAKKU_DEVELOP }}'
          projectId: dakku-develop
          channelId: live

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:development

      - name: Deploy
        run: |
          firebase deploy
